name: Ensignia
author: Ivan Vanderbyl
description: Ensignia helps your team make better decisions about packages and dependencies.

inputs:
  sigctl-version:
    description: "The version of sigctl to use"
    required: true
    default: "latest"

runs:
  using: "composite"
  steps:
    - uses: anchore/sbom-action/download-syft@da167eac915b4e86f08b264dbdbc867b61be6f0c # v0.20.5
    - uses: oras-project/setup-oras@22ce207df3b08e061f537244349aac6ae1d214f6 # v1.2.4
    - name: Download sigctl
      shell: bash
      working-directory: ${{ github.action_path }}
      run: |
        oras pull ghcr.io/ensigniasec/sigctl/sigctl-binary:${{ inputs.sigctl-version }}
        tar -xvf ./dist/sigctl_Linux_x86_64.tar.gz -C ./
        chmod +x ./sigctl
        mkdir -p bin
        mv ./sigctl ./bin/sigctl
        echo "${{ github.action_path }}/bin" >> $GITHUB_PATH
