name: Ensignia
author: Ivan Vanderbyl
description: Ensignia helps your team make better decisions about packages and dependencies.

runs:
  using: "composite"
  steps:
    - uses: anchore/sbom-action/download-syft@v0.15.2
    - uses: oras-project/setup-oras@v1.1.0
    - name: Download sigctl
      shell: bash
      working-directory: ${{ github.action_path }}
      run: |
        oras pull ghcr.io/ensigniasec/sigctl/sigctl-binary:latest
        tar -xvf ./dist/sigctl_Linux_x86_64.tar.gz -C ./
        chmod +x ./sigctl
        echo "$PATH"
        echo "${{ github.action_path }}/sigctl" >> $GITHUB_PATH

    - name: "Log PATH"
      shell: bash
      run: |
        echo "$PATH"
